### ISSUE TITLE
Does not update Temp/Humidity Data from ESPhome with 

### ISSUE THREAD

**Issue by sommertrip** [lucavb/homebridge-esphome-ts#12]
Hi, I've configured the plugin with homebridge, in use with [https://esphome.io/components/sensor/xiaomi_lywsd02.html](https://esphome.io/components/sensor/xiaomi_lywsd02.html)
I setup and configured the plugin properly, but it does not update the data from esp32 anymore, just the status from the setup is still there.

**Comment by lucavb** [comment]
And you know that your device sends those updates because you have seen the values change in something like homebridge or the web gui?
