### ISSUE TITLE
Doesn't seem to reconnect if connection lost

### ISSUE THREAD

**Issue by slynn1324** [lucavb/homebridge-esphome-ts#14]
If a device goes offline, homebridge doesn't seem to attempt to reconnect to it automatically and the sensor readings obviously go stale.  If I restart homebridge after the sensor is back online, it reconnects fine and works normally.

**Comment by slynn1324** [comment]
Thanks for responding -- honestly, I uninstalled it and changed my devices up to write to a mqtt server - as I decided I wanted to pull the sensor data into influxdb for reporting as well as into homebridge.  The config I was using was really minimal: 

        {
            "devices": [
                {
                    "host": "office_temperature",
                    "password": "***"
                }
            ],
            "debug": true,
            "platform": "esphome"
        }

This was a simple temperature sensor device sitting next to me.  To test it, I had it up and running and homebridge was reporting correctly, and then I pulled the plug out of the device.  After a few seconds I plugged it back in, and put my finger on the thermometer sensor so that it would report a higher number... and it never updated homebridge again.  As soon as I restarted homebridge, I reconnected to the sensor fine and started reporting the higher number.  

That was kind of the extent of my testing at this time - as I decided to use mqtt for additional reasons as well.

**Comment by lucavb** [comment]
Hmm in theory I implemented a reconnect feature in to the underlying library to do the communication. I can test this again.

**Comment by lucavb** [comment]
Update: I haven't lost track of this. There is an issue. I will try and work on it.

**Comment by lucavb** [comment]
Alright, so in German there is a saying that basically means "good things take a while". As a matter of fact I just released version 1.1.0 to npm. Could you give this version a shot assuming you are still using it?

`npm i -g homebridge-esphome-ts@1.1.0`
