### ISSUE TITLE
esphome-ts can't start

### ISSUE THREAD

**Issue by phnxwang** [lucavb/homebridge-esphome-ts#2]
Hi, 
I want to use homebridge-esphome-ts to control esphome switch in homekit, but when install this plugin, homebridge can't start and report below error,  could you help get what wrong for my config or setup?

[4/23/2020, 10:21:44 AM] TypeError: Cannot read property 'forEach' of undefined
    at EsphomePlatform.onHomebridgeDidFinishLaunching (/homebridge/node_modules/homebridge-esphome-ts/dist/index.js:32:29)
    at API.<anonymous> (/homebridge/node_modules/homebridge-esphome-ts/node_modules/homebridge-ts-helper/dist/index.js:21:18)
    at API.emit (events.js:322:22)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:103:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)

config.json:
        {
            "platform": "esphome",
            "device": [
                {
                    "host": "light_bedroom.local",
                }
            ]
        }

**Comment by lucavb** [comment]
You are missing an s at device. That’s why it is crashing

**Comment by phnxwang** [comment]
Appreciate for your quickly reply, issue solved. thanks very much

**Comment by lucavb** [comment]
No problem. Just one hint, there is a bug at the moment where the connection dies after some time. I am eager to fix this, as soon as I have time.

**Comment by phnxwang** [comment]
Sorry but now have a strange problem, I can't control the switch by Homekit, but can get realtime feedback in Homekit when light turn on or off, could you kindly support how to figure out the mistake?  API has filled in ESPHOME config, and controled OK by homeassistant.

**Comment by lucavb** [comment]
Maybe start by telling me what switch you are using. Paste the config for the device please. Make sure to omit anything sensitive, such as passwords.

**Comment by phnxwang** [comment]
Sure,
device is something like ESP8266 but I don't know detail type, config as below:
esphome:
  name: light_bedroom
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: "OpenWrt"
  password: "***"
  ap:
    ssid: "Light-Bedroom Fallback Hotspot"
    password: ""
captive_portal:
logger:
api:
ota:
binary_sensor:
  - platform: gpio    
    pin: 
      number: GPIO0
      mode: INPUT_PULLUP
    name: "switch_bedroom"
    on_state:
      - switch.toggle: relay1
    internal: yes
switch:
  - platform: gpio
    name: "light-bedroom"
    pin: GPIO12
    id: relay1

**Comment by lucavb** [comment]
Okay, I haven't seen any configurations like those yet. Could you please try what I posted here, and tell me what the output was. It should log some JSON to where ever you check your homebridge logs

https://github.com/lucavb/homebridge-esphome-ts/issues/1#issuecomment-615902156

**Comment by lucavb** [comment]
Also I just released beta.6, which includes this debug feature, a newer version of esphome-ts, and most notably for you I guess, a fix to the switch component implementation. Maybe you want to give that one a try.

**Comment by phnxwang** [comment]
Hi lucavb, thanks for your suggest, I will try beta6 later and feedback you.

**Comment by phnxwang** [comment]
Hi lucavb, beta6 seem work perfectly, thanks for your work! :+1:

**Comment by lucavb** [comment]
Glad to hear it.
