### ISSUE TITLE
API does not report being connected

### ISSUE THREAD

**Issue by Klariff** [lucavb/homebridge-esphome-ts#3]
This causes the reboot behavior every 15 minutes due to the lack of connection to the API

**Comment by lucavb** [comment]
Could you be a bit clearer on what this is? Have you configured everything properly? Please share your configs for both homebridge and your esp device. Keep in mind to remove sensitive information!

**Comment by Klariff** [comment]
I don't seem to have the connection defined from the api settings on my ESP8266, how should these settings be?

**Comment by lucavb** [comment]
I can only refer you to the README unless you supply me with the requested information.

**Comment by Klariff** [comment]
Okay, these are my configuration files.

ESPHOME:

`esphome:
  name: mod
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: "XXXXX"
  password: "XXXXX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "XXXXXXX"
    password: "XXXXXXXX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:


ota:

switch:
  - platform: gpio
    name: "Mod"
    pin: D7
    inverted: True

web_server:
  port: 5180

`
HOMEBRIDGE:

`        {
            "platform": "ESPHomePlatform",
            "devices": [
                {
                    "name": "Mod",
                    "host": "192.168.1.177",
                    "type": "switch",
                    "id": "mod",
                    "port": 5180
                }
            ]
        }`

As you can see, my ESPHOME file does not contain any parameters in the api section, contrary to what is mentioned in your README, so I would like to know how I should indicate this parameter

**Comment by lucavb** [comment]
That is a different plugin. This is homebridge-esphome-ts, you are talking about the now deprecated plugin for esphome.

**Comment by Klariff** [comment]
Oh, that was very stupid of me. Anyway, I'd like to know if I have to put anything in the api section

**Comment by lucavb** [comment]
Well I don’t know that, since that is not plugin. But the plugin section as far as I know only has to two keys. Port and password. But you might want to consult the documentation for that other plugin and the official documentation for esphome.

**Comment by Klariff** [comment]
Excellent, I managed to make it work by defining the api port from esphome, thanks for your help, by the way I would like to know if it is possible to add a name attribute to the device from homebridge so it can be recognized locally that way

**Comment by lucavb** [comment]
Are you know talking about my plugin?

**Comment by Klariff** [comment]
Yes

**Comment by lucavb** [comment]
Well it is taking whatever name you have setup in your esphome config. So the easiest way would be to just change the name there.

**Comment by Klariff** [comment]
I know, but it would be interesting as an optional parameter to be able to modify it locally in homebridge

**Comment by Klariff** [comment]
`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> websocket@1.0.31 install /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

sh: 1: cannot create builderror.log: Permission denied
+ homebridge-lgwebos-tv@0.7.19
added 126 packages from 106 contributors in 28.748s`
