### ISSUE TITLE
homebridge-esphome-ts vs mqtt

### ISSUE THREAD

**Issue by JMarceloCasanova** [lucavb/homebridge-esphome-ts#35]
Is this better than setting up mqtt in homebridge(homebridge-mqttthing) and esphome? 
Why/How ?

**Comment by lucavb** [comment]
Quite frankly I have always found MQTT a bit confusing to setup however I also didn't spend that much time for a deep dive either. Nevertheless this plugin talks directly to your ESPs and gets its updates that way, so you don't have to setup an MQTT server.

So I guess that would be the main difference. In the end both plugins should do the same thing.

**Comment by JMarceloCasanova** [comment]
Thanks, I'm having some problems with my MQTT server myself, maybe your plugin will solve everything ;)
