### ISSUE TITLE
The plugin don't working

### ISSUE THREAD

**Issue by joaoreni** [lucavb/homebridge-esphome-ts#6]
Hi,

In the log i'm getting this message:
"The plugin "homebridge-esphome-ts" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!"

also, i get this error:
"Error: The requested platform 'esphome-ts' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)"

the config file is:
        {
            "platform": "esphome-ts",
            "devices": [
                {
                    "host": "quarto.local"
                }
            ],
            "debug": true
        }

when i use the platform with "esphome" without the "-ts", the second error does't happen. But in both ways, the homebridge keeps restarting with the message: "Got SIGTERM, shutting down Homebridge..."

thanks for the help.

**Comment by lucavb** [comment]
The first should be fixed with beta 12, the second isn't exactly a bug. That's what I have written in the documentation.

**Comment by joaoreni** [comment]
Well, i've updated to beta 12 and the first warning is gone.

the second issue i just have used "platform": "esphome", without the "-ts" and its working!

now i have 4 devices in my esp32 and i'll increase the number of devices soon as i can.

in time, i want to tell you: when we use the configuration on the form, when we go to config.json file from homebridge, in the script use "platform": "esphome-ts" automatically with the device configured.

Thanks for the help.
![image](https://user-images.githubusercontent.com/64034018/82276292-38aa9b00-995b-11ea-977e-f290ce9585be.png)
![image](https://user-images.githubusercontent.com/64034018/82276315-4e1fc500-995b-11ea-9d19-6c2610e45b2c.png)

**Comment by lucavb** [comment]
Ah that's where you got it from. okay that is indeed a bug. Thank you.
