### ISSUE TITLE
Light Accessory is not registered to HomeBridge if ESPHome light has 'effects'

### ISSUE THREAD

**Issue by heronog** [lucavb/homebridge-esphome-ts#9]
When using the latest Homebridge (v1.1.1) and a light configured in an ESPHome device, the light does not get registered as an accessory in HomeBridge if there are 'effects' configured.

from the HomeBridge log
[esphome] {} undefined

But from the ESPHome device log:
[D][api.connection:583]: Client 'esphome-ts (192.168.1.5)' connected successfully!

After removing the 'effects' configuration from the ESPHome YAML file the light is registered correctly.

Light effects documentation in ESPHome https://esphome.io/components/light/index.html#light-effects

**Comment by lucavb** [comment]
Can you show me what it outputs when you add the debug parameter? Also maybe share your esphome config for the plugin and your device. Make sure to remove sensitive information before posting it.

**Comment by heronog** [comment]
the ESPHome configuration, with the effects configuration.

`esphome:
  name: bathroom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "xxxxxxx"
  password: "xxxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bathroom Fallback Hotspot"
    password: "xxxxxxxx"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxxxxx"

ota:
  password: "xxxxx"

light:
  - platform: neopixelbus
    type: GRB
    pin: GPIO3
    num_leds: 20
    name: "Bathroom Light"
    variant: 400KBPS
    default_transition_length: 0s
    effects:
      - addressable_random_twinkle:
          progress_interval: 250ms
      - addressable_fireworks:
      - addressable_flicker: 
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 100ms
          scan_width: 6`

This is the log from the plugin  in homebridge using 'debug'
`[esphome] {} undefined`

The fix is to comment out the 'effects' section. This makes the plugin work correctly and the accessory shows up and works normally.

**Comment by lucavb** [comment]
Hmm, interesting. Alright that description I can try and take a look at it nexuses next week.

**Comment by lucavb** [comment]
Okay so the good news is I can reproduce the error, the bad news is I am not sure if I am able to do something about it. Esphome seems to omit the `ListEntitiesLightResponse` event when effects are defined. However, without that event my plugin isn't learning basic information about our light. I am receiving an update event so my plugin knows that are is A light but has no information about it otherwise. In my opinion, the next step would be to query esphome.

**Comment by heronog** [comment]
OK, will bring it up to ESPHome.

**Comment by heronog** [comment]
Thanks @lucavb !
